# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: 'dikshapool'

steps:
- script: |
    echo This is build pipeline.
    echo it is working with file > file.txt
    ls -la
  displayName: 'Build Stage'

  


