# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  name: 'newdeppool'

steps:
- script: |
    echo This is build pipeline.
    echo it is working with file > file.txt
    ls -la
    pwd
    zip -r src.zip ./src
    ls -la
    cp src.zip $(Build.ArtifactStagingDirectory)/.
    ls -la
  displayName: 'Build Stage'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
  